version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pizza
      POSTGRES_USER: pizza-admin
      POSTGRES_DB: pizza-db
  dotnet:
    build: .
    ports:
      - "8080:80"
      - "4433:443"
    depends_on:
      - db