version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyPassword1234"
    network_mode: host
  dotnet:
    build: .
    depends_on:
      - db
    network_mode: host